Store failed builds and build scans
gradle/bt-dev-prod-data-collector pull request #14
Opened 2021-11-02 00:41 UTC by blindpirate

See https://github.com/gradle/gradle-private/issues/2982

We want to track the failed builds without build scans.

2021-11-02 11:11 UTC, wolfs requested changes

2021-11-02 11:11 UTC, wolfs commented on teamcity-export/src/main/java/org/gradle/devprod/collector/teamcity/TeamCityResponse.java
> +        private String startDate;
Why doesn't Jackson take care of parsing the time to a `java.util.time` format?

2021-11-02 11:11 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +        // this is triggered once per hour, let's make the timespan a bit longer
The query runs every 10 minutes, right?

2021-11-02 11:11 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    val httpClient = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.ALWAYS).build()
Don't use `HttpClient`, use `RestTemplate` or `WebClient`.

2021-11-02 11:11 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    val objectMapper = ObjectMapper()
I think we should use Spring's built-in facilities. I am pretty sure the object mapper has been registered as a been somewhere already.

2021-11-03 05:37 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +        val start = end.minus(61, ChronoUnit.MINUTES)
This has been moved out of the method. Besides, I don't understand why we need 5 days if the job is scheduled every hour.

2021-11-03 05:38 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    fun initUrl(pipeline: String): String {
Do you mean "this should **NOT** be called"?

2021-11-03 05:39 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +            "failedToStart" to "true",
I remember in some cases we would like to track the failedToStart builds, for example versioned settings problems?

2021-11-03 05:39 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +        return "https://builds.gradle.org/app/rest/builds/?locator=${locators.entries.joinToString(",") { "${it.key}:${it.value}" }}&fields=$fields&count=$pageSize"
Done.

2021-11-03 05:39 UTC, blindpirate commented on build-platform/build.gradle.kts
> +        api("com.fasterxml.jackson.core:jackson-core:2.13.0")
Done.

2021-11-03 05:40 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    fun loadFailedBuilds(): Sequence<TeamCityBuild> =
Because rest client doesn't support `affectedProject()` locator, it only supports buildconfiguration locator. To use rest client, we have to fetch all build configurations and loop - that's a lot.

2021-11-03 05:44 UTC, blindpirate commented on teamcity-export/src/main/java/org/gradle/devprod/collector/teamcity/TeamCityResponse.java
> +        private String startDate;
The POJO is generated by a plugin and it doesn't support `@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "")` out-of-the-box. I don't like to manually modify the generated POJO since it maybe a burden for maintaining.

2021-11-03 05:45 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +        // this is triggered once per hour, let's make the timespan a bit longer
Yeah, I make it run every hour.

2021-11-03 05:45 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    val httpClient = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.ALWAYS).build()
Done.

2021-11-03 05:45 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    val objectMapper = ObjectMapper()
Done.

2021-11-03 08:33 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    fun WebClient.RequestHeadersSpec<*>.accept(accept: String): WebClient.RequestHeadersSpec<*> = header("Accept", accept)
There is already an `accept()` method on `RequestHeadersSpec`, no need to define our own.

2021-11-03 08:33 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +            "failedToStart" to "true",
I'd not include them for now.

2021-11-03 08:33 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    private val rfc822: DateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss").withZone(ZoneId.systemDefault())
Seems we are now using two styles for `private`: In the same line or just above. We probably should decide on one style at some point and then add some linting. That is for another PR though.

2021-11-03 08:33 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityExport.kt
> +        teamcityClientService.loadFailedBuilds().store()
Maybe we should also add a println here as we do above for `loadTriggerBuilds`?

2021-11-03 08:33 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +                Instant.now().minus(1, ChronoUnit.DAYS),
If we can, we should have a logic like:
- On startup, load builds for the last day (5 days?)
- For each trigger afterwards, only load the builds from the last time we triggered.

I currently don't know how `sinceDate` works, so when the query would return long running builds which have not finished since the last invocation. If using 1 day is not too expensive, we can also always use that.

2021-11-04 09:16 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +    fun loadFailedBuilds(): Sequence<TeamCityBuild> =
This is done in https://github.com/JetBrains/teamcity-rest-client/pull/105

2021-11-04 14:26 UTC, wolfs approved these changes
I think that looks good now. I left some minor comments.

2021-11-04 14:26 UTC, wolfs commented on teamcity-export/src/main/java/org/gradle/devprod/collector/teamcity/TeamCityResponse.java
> +        public static class RevisionsBean {
Is it normal for the generation to add all the bean classes inside of the top-level class? I'd prefer having them in extra files.

2021-11-04 14:26 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamCityBuild.kt
> +    composite == true
```suggestion
    composite
```

I don't understand. Can `composite` be `null`?

2021-11-04 14:26 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityClientService.kt
> +            "untilDate" to formatRFC822(end),
I wonder, do we even need an end date?

2021-11-04 14:26 UTC, wolfs commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityExport.kt
> +        else TEAMCITY_BUILD.FINISHED.get(latestFailedBuild)!!.toInstant().minus(1, ChronoUnit.DAYS)
I still don't know how `sinceDate` works, though shouldn't we use something like `TEAMCITY_BUILD.STARTED` instead of `FINISHED`? Though I suppose it doesn't really matter that much, given that we substract a day anyway.

2021-11-04 14:26 UTC, wolfs commented on persistence/src/main/resources/db/migration/V1.15__Add_buildscan_url_is_composite_to_teamcity_build.sql
> +    add composite boolean;
Both of those fields could be non-null, right?

2021-11-05 06:18 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamCityBuild.kt
> +    composite == true
The declaration is `Boolean?`:

```
interface Build {
    val id: BuildId
    val buildConfigurationId: BuildConfigurationId
    val buildNumber: String?
    val status: BuildStatus?
    val branch: Branch
    val state: BuildState
    val personal: Boolean
    val name: String
    val canceledInfo: BuildCanceledInfo?
    val comment: BuildCommentInfo?

    val composite: Boolean?
...
```

2021-11-05 06:26 UTC, blindpirate commented on persistence/src/main/resources/db/migration/V1.15__Add_buildscan_url_is_composite_to_teamcity_build.sql
> +    add composite boolean;
Yes, but we should not use default value right?

2021-11-05 06:27 UTC, blindpirate commented on teamcity-export/src/main/java/org/gradle/devprod/collector/teamcity/TeamCityResponse.java
> +        public static class RevisionsBean {
Interesting, I would prefer using a single class because it would make it easier to maintain - copy the JSON sample, paste, generate.

2021-11-05 06:29 UTC, blindpirate commented on teamcity-export/src/main/kotlin/org/gradle/devprod/collector/teamcity/TeamcityExport.kt
> +        else TEAMCITY_BUILD.FINISHED.get(latestFailedBuild)!!.toInstant().minus(1, ChronoUnit.DAYS)
Yeah... I don't know either. Let's keep like this unless we run into issues.

2021-11-08 05:17 UTC, merged

2021-11-08 05:17 UTC, blindpirate commented
It seems to be working.