Add ktlint
gradle/bt-dev-prod-data-collector pull request #15
Opened 2021-11-05 06:38 UTC by blindpirate

With default configuration.

2021-11-08 07:51 UTC, wolfs requested changes

2021-11-08 07:51 UTC, wolfs commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +    "ktlint"("com.pinterest:ktlint:$ktlintVersion")
Any reason for not using `org.jlleitschuh.gradle.ktlint`? Though I'd probably prefer if we'd be using `ktlint` through `spotless`: https://plugins.gradle.org/plugin/com.diffplug.spotless

2021-11-09 03:16 UTC, blindpirate commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +    "ktlint"("com.pinterest:ktlint:$ktlintVersion")
Good to know! I applied spotless for kt/gradle.kts files, though the default format of gradle.kts files seems to be a bit weird.

2021-11-09 08:15 UTC, wolfs commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +            target("**/*.gradle.kts")
I think the default would be better (`*.gradle.kts`), since the above instructs Gradle to walk all the files in the root project directory. Then I'd also apply it to all projects.

I suppose you changed this to `**/...`, since you want to check the buildSrc scripts as well? Then I'd add them manually via separate includes.

2021-11-09 08:15 UTC, wolfs commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +            ktfmt(ktfmtVersion)
I don't understand why we now use ktlint and ktfmt. Wouldn't one be enough?

2021-11-09 08:15 UTC, wolfs commented on buildSrc/src/main/kotlin/data-collector-common.gradle.kts
> +plugins { java }
I agree that this is strange. I suppose this is from `ktfmt`, since `ktlint` doesn't have problems with multiline plugin statements I think.

2021-11-10 05:35 UTC, blindpirate commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +            target("**/*.gradle.kts")
Yep. Now the patterns are separated.

2021-11-10 05:35 UTC, blindpirate commented on buildSrc/src/main/kotlin/configure-ktlint.gradle.kts
> +            ktfmt(ktfmtVersion)
I thought `ktfmt` is necessary for `spotlessApply` but seems like it's not. Removed.

2021-11-10 05:35 UTC, blindpirate commented on buildSrc/src/main/kotlin/data-collector-common.gradle.kts
> +plugins { java }
Yep. Rmeoved `ktfmt` and it seems good now.

2021-11-10 09:23 UTC, wolfs approved these changes
I think that looks good now. I'd like us to get rid of the `allprojects` block, though that can happen in a follow up PR.

2021-11-11 02:32 UTC, merged